### ISSUE TITLE
Fix test issues when gambit and lrs are not installed

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#57]
Doctested on my ubuntu box and got (will keep this off my ubuntu machine until it is sorted), is there a way to write conditional tests?

---

File "normal_form_game.py", line 71, in sage.game_theory.normal_form_game.NormalFormGame
Failed example:
    g.obtain_Nash()
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame[21]>", line 1, in <module>
        g.obtain_Nash()
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 87, in sage.game_theory.normal_form_game.NormalFormGame
Failed example:
    g.obtain_Nash()
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame[25]>", line 1, in <module>
        g.obtain_Nash()
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 99, in sage.game_theory.normal_form_game.NormalFormGame
Failed example:
    g.obtain_Nash()
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame[28]>", line 1, in <module>
        g.obtain_Nash()
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 129, in sage.game_theory.normal_form_game.NormalFormGame
Failed example:
    g.obtain_Nash()
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame[33]>", line 1, in <module>
        g.obtain_Nash()
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 376, in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
Failed example:
    g.obtain_Nash(algorithm='lrs')
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash[3]>", line 1, in <module>
        g.obtain_Nash(algorithm='lrs')
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 430, in obtain_Nash
        raise NotImplementedError("lrs is not installed")
    NotImplementedError: lrs is not installed

---

File "normal_form_game.py", line 378, in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
Failed example:
    g.obtain_Nash(algorithm='lrs', maximization=False)
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash[4]>", line 1, in <module>
        g.obtain_Nash(algorithm='lrs', maximization=False)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 430, in obtain_Nash
        raise NotImplementedError("lrs is not installed")
    NotImplementedError: lrs is not installed

---

File "normal_form_game.py", line 390, in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
Failed example:
    g.obtain_Nash(maximization=False)
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash[8]>", line 1, in <module>
        g.obtain_Nash(maximization=False)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 406, in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
Failed example:
    fivegame.obtain_Nash()
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash[12]>", line 1, in <module>
        fivegame.obtain_Nash()
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 424, in obtain_Nash
        raise NotImplementedError("gambit is not installed")
    NotImplementedError: gambit is not installed

---

File "normal_form_game.py", line 408, in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
Failed example:
    fivegame.obtain_Nash(algorithm='lrs')
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash[13]>", line 1, in <module>
        fivegame.obtain_Nash(algorithm='lrs')
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 430, in obtain_Nash
        raise NotImplementedError("lrs is not installed")
    NotImplementedError: lrs is not installed

---

File "normal_form_game.py", line 461, in sage.game_theory.normal_form_game.NormalFormGame._solve_LCP
Failed example:
    c._solve_LCP(maximization=True)
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame._solve_LCP[3]>", line 1, in <module>
        c._solve_LCP(maximization=True)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 464, in _solve_LCP
        from gambit import Game
    ImportError: No module named gambit

---

File "normal_form_game.py", line 496, in sage.game_theory.normal_form_game.NormalFormGame._solve_lrs
Failed example:
    C._solve_lrs(A, B)
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame._solve_lrs[3]>", line 1, in <module>
        C._solve_lrs(A, B)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 530, in _solve_lrs
        process = Popen(['nash', g1_name, g2_name], stdout=PIPE)
      File "lazy_import.pyx", line 358, in sage.misc.lazy_import.LazyImport.__call__ (sage/misc/lazy_import.c:3000)
      File "/home/vince/sage/local/lib/python/subprocess.py", line 711, in **init**
        errread, errwrite)
      File "/home/vince/sage/local/lib/python/subprocess.py", line 1308, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

---

File "normal_form_game.py", line 512, in sage.game_theory.normal_form_game.NormalFormGame._solve_lrs
Failed example:
    biggame._solve_lrs(p1, p2)
Exception raised:
    Traceback (most recent call last):
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 480, in _run
        self.execute(example, compiled, test.globs)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 839, in execute
        exec compiled in globs
      File "<doctest sage.game_theory.normal_form_game.NormalFormGame._solve_lrs[7]>", line 1, in <module>
        biggame._solve_lrs(p1, p2)
      File "/home/vince/sage/local/lib/python2.7/site-packages/sage/game_theory/normal_form_game.py", line 530, in _solve_lrs
        process = Popen(['nash', g1_name, g2_name], stdout=PIPE)
      File "/home/vince/sage/local/lib/python/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/home/vince/sage/local/lib/python/subprocess.py", line 1308, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

---

4 items had failures:
   4 of  35 in sage.game_theory.normal_form_game.NormalFormGame
   1 of   5 in sage.game_theory.normal_form_game.NormalFormGame._solve_LCP
   2 of   9 in sage.game_theory.normal_form_game.NormalFormGame._solve_lrs
   5 of  15 in sage.game_theory.normal_form_game.NormalFormGame.obtain_Nash
## sage -t normal_form_game.py  # 12 doctests failed

Total time for all tests: 0.3 seconds
    cpu time: 0.3 seconds
    cumulative wall time: 0.3 seconds

**Comment by drvinceknight** [comment]
Need to include thing about optional tag in docs (clarifying what it means).
